#!/usr/bin/env bash


# office-31
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office --output_dir log/TTSA/office31 --s_dset_path /data1/TL/data/list/office/amazon_31.txt --t_dset_path /data1/TL/data/list/office/webcam_31.txt --t_test_path /data1/TL/data/list/office/webcam_31.txt --epochs 30 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office --output_dir log/TTSA/office31 --s_dset_path /data1/TL/data/list/office/amazon_31.txt --t_dset_path /data1/TL/data/list/office/dslr_31.txt --t_test_path /data1/TL/data/list/office/dslr_31.txt --epochs 30 --iters-per-epoch 500 --lambda0 0.25 --lr 0.001  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office --output_dir log/TTSA/office31 --s_dset_path /data1/TL/data/list/office/webcam_31.txt --t_dset_path /data1/TL/data/list/office/amazon_31.txt --t_test_path /data1/TL/data/list/office/amazon_31.txt --epochs 30 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office --output_dir log/TTSA/office31 --s_dset_path /data1/TL/data/list/office/dslr_31.txt --t_dset_path /data1/TL/data/list/office/amazon_31.txt --t_test_path /data1/TL/data/list/office/amazon_31.txt --epochs 30 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office --output_dir log/TTSA/office31 --s_dset_path /data1/TL/data/list/office/dslr_31.txt --t_dset_path /data1/TL/data/list/office/webcam_31.txt --t_test_path /data1/TL/data/list/office/webcam_31.txt --epochs 30 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office --output_dir log/TTSA/office31 --s_dset_path /data1/TL/data/list/office/webcam_31.txt --t_dset_path /data1/TL/data/list/office/dslr_31.txt --t_test_path /data1/TL/data/list/office/dslr_31.txt --epochs 30 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1



# Office-Home
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/Art_65.txt --t_dset_path /data1/TL/data/list/home/Clipart_65.txt --t_test_path /data1/TL/data/list/home/Clipart_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/Art_65.txt --t_dset_path /data1/TL/data/list/home/Product_65.txt --t_test_path /data1/TL/data/list/home/Product_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/Art_65.txt --t_dset_path /data1/TL/data/list/home/RealWorld_65.txt --t_test_path /data1/TL/data/list/home/RealWorld_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/Clipart_65.txt --t_dset_path /data1/TL/data/list/home/Art_65.txt --t_test_path /data1/TL/data/list/home/Art_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/Clipart_65.txt --t_dset_path /data1/TL/data/list/home/Product_65.txt --t_test_path /data1/TL/data/list/home/Product_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/Clipart_65.txt --t_dset_path /data1/TL/data/list/home/RealWorld_65.txt --t_test_path /data1/TL/data/list/home/RealWorld_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/Product_65.txt --t_dset_path /data1/TL/data/list/home/Art_65.txt --t_test_path /data1/TL/data/list/home/Art_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/Product_65.txt --t_dset_path /data1/TL/data/list/home/Clipart_65.txt --t_test_path /data1/TL/data/list/home/Clipart_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/Product_65.txt --t_dset_path /data1/TL/data/list/home/RealWorld_65.txt --t_test_path /data1/TL/data/list/home/RealWorld_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/RealWorld_65.txt --t_dset_path /data1/TL/data/list/home/Art_65.txt --t_test_path /data1/TL/data/list/home/Art_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/RealWorld_65.txt --t_dset_path /data1/TL/data/list/home/Clipart_65.txt --t_test_path /data1/TL/data/list/home/Clipart_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet50 --seed 2 --dset office-home --output_dir log/TTSA/home --s_dset_path /data1/TL/data/list/home/RealWorld_65.txt --t_dset_path /data1/TL/data/list/home/Product_65.txt --t_test_path /data1/TL/data/list/home/Product_65.txt --epochs 40 --iters-per-epoch 500 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1




# visda
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 4 --center_crop --dset visda --output_dir log/TTSA/visda --s_dset_path /data1/TL/data/list/visda2017/synthetic_12.txt --t_dset_path /data1/TL/data/list/visda2017/real_12.txt --t_test_path /data1/TL/data/list/visda2017/real_12.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.001  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1 --MI 0.1




# DomainNet
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_test_path /data1/TL/data/list/domainnet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_test_path /data1/TL/data/list/domainnet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_test_path /data1/TL/data/list/domainnet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_test_path /data1/TL/data/list/domainnet/real_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_test_path /data1/TL/data/list/domainnet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
#
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_test_path /data1/TL/data/list/domainnet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_test_path /data1/TL/data/list/domainnet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_test_path /data1/TL/data/list/domainnet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_test_path /data1/TL/data/list/domainnet/real_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_test_path /data1/TL/data/list/domainnet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
#
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_test_path /data1/TL/data/list/domainnet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_test_path /data1/TL/data/list/domainnet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_test_path /data1/TL/data/list/domainnet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_test_path /data1/TL/data/list/domainnet/real_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_test_path /data1/TL/data/list/domainnet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
#
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_test_path /data1/TL/data/list/domainnet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_test_path /data1/TL/data/list/domainnet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_test_path /data1/TL/data/list/domainnet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_test_path /data1/TL/data/list/domainnet/real_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_test_path /data1/TL/data/list/domainnet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
#
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_test_path /data1/TL/data/list/domainnet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_test_path /data1/TL/data/list/domainnet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_test_path /data1/TL/data/list/domainnet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_test_path /data1/TL/data/list/domainnet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_test_path /data1/TL/data/list/domainnet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
#
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_dset_path /data1/TL/data/list/domainnet/clipart_train.txt --t_test_path /data1/TL/data/list/domainnet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_dset_path /data1/TL/data/list/domainnet/infograph_train.txt --t_test_path /data1/TL/data/list/domainnet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_dset_path /data1/TL/data/list/domainnet/painting_train.txt --t_test_path /data1/TL/data/list/domainnet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_dset_path /data1/TL/data/list/domainnet/quickdraw_train.txt --t_test_path /data1/TL/data/list/domainnet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
python3 train_TTSA.py --gpu_id 0 --arch resnet101 --seed 2 --center_crop --dset domainnet --output_dir log/TTSA/domainnet --s_dset_path /data1/TL/data/list/domainnet/sketch_train.txt --t_dset_path /data1/TL/data/list/domainnet/real_train.txt --t_test_path /data1/TL/data/list/domainnet/real_test.txt --epochs 30 --iters-per-epoch 1000 --lambda0 0.25 --lr 0.008  --gamma 0.001 --beta 0.1 --eta 0.5 --alpha 0.1
